name: Build Binaries

# 在 push tag 或手动触发时运行
on:
  push:
    tags:
      - "v*.*.*"   # 例如 v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      # 1) 获取源码
      - name: Checkout source
        uses: actions/checkout@v4

      # 2) 安装 Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3) 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # 4) Windows 额外安装 VC++ 2013 运行时
      - name: Install VC++ 2013 Redistributable
        if: runner.os == 'Windows'
        run: |
          choco install vcredist2013 -y

      # 5) 构建 (针对不同平台的图标分别处理)
      - name: Build Windows executable
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconfirm --onefile --icon "src/LightAuth_logo .ico" main.py

      - name: Build macOS app
        if: runner.os == 'macOS'
        run: |
          pyinstaller --noconfirm --windowed --icon "src/LightAuth_logo.icns" main.py

      # 6) 上传构建结果
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LightAuth-${{ runner.os }}
          path: |
            dist/**/* 