name: Build Binaries with Nuitka

on:
  push:
    branches: ["**"]  # 任意分支的 push 都触发
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install VC++ 2013 Redistributable
        if: runner.os == 'Windows'
        run: |
          choco install vcredist2013 -y

      - name: Install VC++ 2015-2022 Redistributable
        if: runner.os == 'Windows'
        run: |
          choco install vcredist140 -y

      - name: Build Windows executable
        if: runner.os == 'Windows'
        run: |
          python -m nuitka --standalone --windows-disable-console --assume-yes-for-downloads --show-progress --windows-icon-from-ico="src/LightAuth_logo.ico" --enable-plugin=pyqt6 --include-package=pyzbar --include-package-data=pyzbar --include-data-dir=src=src --output-dir=dist LightAuth.py

      - name: Build macOS app
        if: runner.os == 'macOS'
        run: |
          python -m nuitka --standalone --assume-yes-for-downloads --macos-create-app-bundle --macos-app-icon="src/LightAuth_logo.icns" --disable-console --enable-plugin=pyside6 --include-package=pyzbar --include-package-data=pyzbar --include-data-dir=src=src --output-dir=dist LightAuth.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightAuth-${{ runner.os }}
          path: |
            dist/**/*

 