name: Build Binaries with PyInstaller

on:
  push:
    branches: ["**"]  # 任意分支的 push 都触发
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Install VC++ 2013 Redistributable
        if: runner.os == 'Windows'
        run: |
          choco install vcredist2013 -y

      - name: Build Windows executable
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconfirm --onefile --icon "src/LightAuth_logo .ico" main.py

      - name: Build macOS app
        if: runner.os == 'macOS'
        run: |
          pyinstaller --noconfirm --windowed --icon "src/LightAuth_logo.icns" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LightAuth-${{ runner.os }}
          path: |
            dist/**/*

 